---
- name: Install formulas
  become: no
  homebrew:
    pkg:
      - htop
      - colima
      - neovim
      - tfenv
      - go
      - jq
      - nvm
      - pyenv
      - tfenv
      - kubectl
      - helm
      - zsh-syntax-highlighting
      - telnet
      - awscli
      - qwen-code
      - gemini-cli
      - openjdk
- name: openjdk post install fix
  shell: |
    ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
# Ignore for now
# - name: Install cask formulas
#   become: no
#   homebrew_cask:
#     pkg:
#       - google-chrome
#       - iterm2
#       - dbeaver-community
#       - slack
