---
- name: Install formulas
  become: no
  homebrew:
    pkg:
      - colima
      - neovim
      - tfenv
      - go
      - jq
      - nvm
      - pyenv
      - tfenv
      - kubectl
      - helm
      - zsh-syntax-highlighting
      - telnet
      - awscli
# Ignore for now
# - name: Install cask formulas
#   become: no
#   homebrew_cask:
#     pkg:
#       - google-chrome
#       - iterm2
#       - dbeaver-community
#       - slack
